/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 14 18:10:00 GMT 2020
 */

package main.java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import main.java.Cliente;
import main.java.ComparadorKm;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComparadorKm_ESTest extends ComparadorKm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      Cliente cliente0 = mock(Cliente.class, new ViolatedAssumptionAnswer());
      doReturn(2239.05172, (-782.50425604)).when(cliente0).getNKm();
      int int0 = comparadorKm0.compare(cliente0, cliente0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      // Undeclared exception!
      try { 
        comparadorKm0.compare((Cliente) null, (Cliente) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.ComparadorKm", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      Cliente cliente0 = mock(Cliente.class, new ViolatedAssumptionAnswer());
      doReturn((-5712.5)).when(cliente0).getNKm();
      Cliente cliente1 = mock(Cliente.class, new ViolatedAssumptionAnswer());
      doReturn((double)(-1)).when(cliente1).getNKm();
      int int0 = comparadorKm0.compare(cliente0, cliente1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      Cliente cliente0 = mock(Cliente.class, new ViolatedAssumptionAnswer());
      doReturn((-5712.5), (-5712.5)).when(cliente0).getNKm();
      int int0 = comparadorKm0.compare(cliente0, cliente0);
      assertEquals((-1), int0);
  }
}
