/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 14 18:05:25 GMT 2020
 */

package main.java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.NoSuchElementException;
import main.java.Menu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Menu_ESTest extends Menu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SystemInUtil.addInputLine("0 - Sair\n ");
      int int0 = Menu.menuLerInt(0, 0, "", "|^m");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SystemInUtil.addInputLine("7");
      int int0 = Menu.menuLerInt(0, 1507, "-", "~fAWdvaq[1O");
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[7];
      SystemInUtil.addInputLine("7");
      stringArray0[0] = "~fAWdvaq[1O";
      Menu menu0 = new Menu(stringArray0);
      menu0.executa();
      int int0 = menu0.getOpcao();
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[3];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.executa();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.executa();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SystemInUtil.addInputLine("0 Sair ");
      // Undeclared exception!
      try { 
        Menu.menuLerInt((-6), (-6), "0 Sair ", "0 Sair ");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SystemInUtil.addInputLine("0 - Sair\n ");
      // Undeclared exception!
      try { 
        Menu.menuLerInt(2, 2, "0 - Sair\n ", (String) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SystemInUtil.addInputLine("0 - Sair\n ");
      String[] stringArray0 = new String[1];
      stringArray0[0] = "fAWdvaq1O";
      Menu menu0 = new Menu(stringArray0);
      menu0.executa();
      SystemInUtil.addInputLine("fAWdvaq1O");
      // Undeclared exception!
      try { 
        menu0.executa();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[6];
      SystemInUtil.addInputLine("7");
      stringArray0[0] = "main.java.Input";
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.executa();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[6];
      Menu menu0 = new Menu(stringArray0);
      int int0 = menu0.getOpcao();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Menu menu0 = null;
      try {
        menu0 = new Menu((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }
}
