/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 14 18:12:02 GMT 2020
 */

package main.java;

import org.junit.Test;
import static org.junit.Assert.*;
import main.java.NaoExistemClientesException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NaoExistemClientesException_ESTest extends NaoExistemClientesException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NaoExistemClientesException naoExistemClientesException0 = new NaoExistemClientesException("{A);tsv^GY 9%[zdd*");
  }
}
