/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 14 18:12:18 GMT 2020
 */

package main.java;

import org.junit.Test;
import static org.junit.Assert.*;
import main.java.VeiculoNaoExisteException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VeiculoNaoExisteException_ESTest extends VeiculoNaoExisteException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VeiculoNaoExisteException veiculoNaoExisteException0 = new VeiculoNaoExisteException("");
  }
}
