/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 14 18:11:32 GMT 2020
 */

package main.java;

import org.junit.Test;
import static org.junit.Assert.*;
import main.java.NaoExistemAlugueresException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NaoExistemAlugueresException_ESTest extends NaoExistemAlugueresException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NaoExistemAlugueresException naoExistemAlugueresException0 = new NaoExistemAlugueresException("");
  }
}
