/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 14 18:11:53 GMT 2020
 */

package main.java;

import org.junit.Test;
import static org.junit.Assert.*;
import main.java.AluguerNaoExisteException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AluguerNaoExisteException_ESTest extends AluguerNaoExisteException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AluguerNaoExisteException aluguerNaoExisteException0 = new AluguerNaoExisteException("ZZ)19ed&{>N&O`*:");
  }
}
