/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 14 18:10:58 GMT 2020
 */

package main.java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import main.java.ComparadorPreco;
import main.java.Veiculo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComparadorPreco_ESTest extends ComparadorPreco_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComparadorPreco comparadorPreco0 = new ComparadorPreco();
      Veiculo veiculo0 = mock(Veiculo.class, new ViolatedAssumptionAnswer());
      doReturn((-3206.118238222037), 608.97736).when(veiculo0).getPreco();
      int int0 = comparadorPreco0.compare(veiculo0, veiculo0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ComparadorPreco comparadorPreco0 = new ComparadorPreco();
      Veiculo veiculo0 = mock(Veiculo.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(veiculo0).getPreco();
      Veiculo veiculo1 = mock(Veiculo.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(veiculo1).getPreco();
      int int0 = comparadorPreco0.compare(veiculo0, veiculo1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ComparadorPreco comparadorPreco0 = new ComparadorPreco();
      // Undeclared exception!
      try { 
        comparadorPreco0.compare((Veiculo) null, (Veiculo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.ComparadorPreco", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComparadorPreco comparadorPreco0 = new ComparadorPreco();
      Veiculo veiculo0 = mock(Veiculo.class, new ViolatedAssumptionAnswer());
      doReturn((double)(-1), (-2896.4533715137254)).when(veiculo0).getPreco();
      int int0 = comparadorPreco0.compare(veiculo0, veiculo0);
      assertEquals(1, int0);
  }
}
